from __future__ import annotations

TEAM_LOGOS: dict[str, dict[str, str]] = {
    "epl": {
        "Arsenal": "https://images.kickoffapi.com/images/logos/42.png?format=webp",
        "Aston Villa": "https://images.kickoffapi.com/images/logos/66.png?format=webp",
        "Bournemouth": "https://images.kickoffapi.com/images/logos/35.png?format=webp",
        "Brentford": "https://images.kickoffapi.com/images/logos/55.png?format=webp",
        "Brighton": "https://images.kickoffapi.com/images/logos/51.png?format=webp",
        "Chelsea": "https://images.kickoffapi.com/images/logos/49.png?format=webp",
        "Coventry": "https://images.kickoffapi.com/images/logos/1346.png?format=webp",
        "Crystal Palace": "https://images.kickoffapi.com/images/logos/52.png?format=webp",
        "Everton": "https://images.kickoffapi.com/images/logos/45.png?format=webp",
        "Fulham": "https://images.kickoffapi.com/images/logos/36.png?format=webp",
        "Hull City": "https://images.kickoffapi.com/images/logos/64.png?format=webp",
        "Ipswich": "https://images.kickoffapi.com/images/logos/57.png?format=webp",
        "Leeds": "https://images.kickoffapi.com/images/logos/63.png?format=webp",
        "Liverpool": "https://images.kickoffapi.com/images/logos/40.png?format=webp",
        "Manchester City": "https://images.kickoffapi.com/images/logos/50.png?format=webp",
        "Manchester United": "https://images.kickoffapi.com/images/logos/33.png?format=webp",
        "Newcastle": "https://images.kickoffapi.com/images/logos/34.png?format=webp",
        "Nottingham Forest": "https://images.kickoffapi.com/images/logos/65.png?format=webp",
        "Sunderland": "https://images.kickoffapi.com/images/logos/746.png?format=webp",
        "Tottenham": "https://images.kickoffapi.com/images/logos/47.png?format=webp",
    },
    "laliga": {
        "Athletic Club": "https://images.kickoffapi.com/images/logos/531.png?format=webp",
        "CA Osasuna": "https://images.kickoffapi.com/images/logos/727.png?format=webp",
        "Club Atlético de Madrid": "https://images.kickoffapi.com/images/logos/530.png?format=webp",
        "Deportivo Alavés": "https://images.kickoffapi.com/images/logos/542.png?format=webp",
        "Elche CF": "https://images.kickoffapi.com/images/logos/797.png?format=webp",
        "FC Barcelona": "https://images.kickoffapi.com/images/logos/529.png?format=webp",
        "Getafe CF": "https://images.kickoffapi.com/images/logos/546.png?format=webp",
        "Levante UD": "https://images.kickoffapi.com/images/logos/539.png?format=webp",
        "Málaga CF": "https://images.kickoffapi.com/images/logos/535.png?format=webp",
        "RC Celta de Vigo": "https://images.kickoffapi.com/images/logos/538.png?format=webp",
        "RC Deportivo La Coruña": "https://images.kickoffapi.com/images/logos/544.png?format=webp",
        "RCD Espanyol de Barcelona": "https://images.kickoffapi.com/images/logos/540.png?format=webp",
        "Rayo Vallecano de Madrid": "https://images.kickoffapi.com/images/logos/728.png?format=webp",
        "Real Betis Balompié": "https://images.kickoffapi.com/images/logos/543.png?format=webp",
        "Real Madrid CF": "https://images.kickoffapi.com/images/logos/541.png?format=webp",
        "Real Racing Club de Santander": "https://images.kickoffapi.com/images/logos/4665.png?format=webp",
        "Real Sociedad de Fútbol": "https://images.kickoffapi.com/images/logos/548.png?format=webp",
        "Sevilla FC": "https://images.kickoffapi.com/images/logos/536.png?format=webp",
        "Valencia CF": "https://images.kickoffapi.com/images/logos/532.png?format=webp",
        "Villarreal CF": "https://images.kickoffapi.com/images/logos/533.png?format=webp",
    },
    "bundesliga": {
        "1. FC Köln": "https://images.kickoffapi.com/images/logos/192.png?format=webp",
        "1899 Hoffenheim": "https://images.kickoffapi.com/images/logos/167.png?format=webp",
        "Bayer Leverkusen": "https://images.kickoffapi.com/images/logos/168.png?format=webp",
        "Bayern München": "https://images.kickoffapi.com/images/logos/157.png?format=webp",
        "Borussia Dortmund": "https://images.kickoffapi.com/images/logos/165.png?format=webp",
        "Borussia Mönchengladbach": "https://images.kickoffapi.com/images/logos/163.png?format=webp",
        "Eintracht Frankfurt": "https://images.kickoffapi.com/images/logos/169.png?format=webp",
        "FC Augsburg": "https://images.kickoffapi.com/images/logos/170.png?format=webp",
        "FC Schalke 04": "https://images.kickoffapi.com/images/logos/174.png?format=webp",
        "FSV Mainz 05": "https://images.kickoffapi.com/images/logos/164.png?format=webp",
        "Hamburger SV": "https://images.kickoffapi.com/images/logos/175.png?format=webp",
        "RB Leipzig": "https://images.kickoffapi.com/images/logos/173.png?format=webp",
        "SC Freiburg": "https://images.kickoffapi.com/images/logos/160.png?format=webp",
        "SC Paderborn 07": "https://images.kickoffapi.com/images/logos/185.png?format=webp",
        "SV Elversberg": "https://images.kickoffapi.com/images/logos/1660.png?format=webp",
        "Union Berlin": "https://images.kickoffapi.com/images/logos/182.png?format=webp",
        "VfB Stuttgart": "https://images.kickoffapi.com/images/logos/172.png?format=webp",
        "Werder Bremen": "https://images.kickoffapi.com/images/logos/162.png?format=webp",
    },
    "ligue1": {
        "Angers": "https://images.kickoffapi.com/images/logos/77.png?format=webp",
        "Auxerre": "https://images.kickoffapi.com/images/logos/108.png?format=webp",
        "Estac Troyes": "https://images.kickoffapi.com/images/logos/110.png?format=webp",
        "LE Havre": "https://images.kickoffapi.com/images/logos/111.png?format=webp",
        "Le Mans": "https://images.kickoffapi.com/images/logos/1298.png?format=webp",
        "Lens": "https://images.kickoffapi.com/images/logos/116.png?format=webp",
        "Lille": "https://images.kickoffapi.com/images/logos/79.png?format=webp",
        "Lorient": "https://images.kickoffapi.com/images/logos/97.png?format=webp",
        "Lyon": "https://images.kickoffapi.com/images/logos/80.png?format=webp",
        "Marseille": "https://images.kickoffapi.com/images/logos/81.png?format=webp",
        "Monaco": "https://images.kickoffapi.com/images/logos/91.png?format=webp",
        "Nice": "https://images.kickoffapi.com/images/logos/84.png?format=webp",
        "Paris FC": "https://images.kickoffapi.com/images/logos/114.png?format=webp",
        "Paris Saint Germain": "https://images.kickoffapi.com/images/logos/85.png?format=webp",
        "Rennes": "https://images.kickoffapi.com/images/logos/94.png?format=webp",
        "Stade Brestois 29": "https://images.kickoffapi.com/images/logos/106.png?format=webp",
        "Strasbourg": "https://images.kickoffapi.com/images/logos/95.png?format=webp",
        "Toulouse": "https://images.kickoffapi.com/images/logos/96.png?format=webp",
    },
    "j1": {
        "Avispa Fukuoka": "https://images.kickoffapi.com/images/logos/316.png?format=webp",
        "Cerezo Osaka": "https://images.kickoffapi.com/images/logos/291.png?format=webp",
        "FC Tokyo": "https://images.kickoffapi.com/images/logos/292.png?format=webp",
        "Fagiano Okayama": "https://images.kickoffapi.com/images/logos/310.png?format=webp",
        "Gamba Osaka": "https://images.kickoffapi.com/images/logos/293.png?format=webp",
        "JEF United Chiba": "https://images.kickoffapi.com/images/logos/301.png?format=webp",
        "Kashima": "https://images.kickoffapi.com/images/logos/290.png?format=webp",
        "Kashiwa Reysol": "https://images.kickoffapi.com/images/logos/281.png?format=webp",
        "Kawasaki Frontale": "https://images.kickoffapi.com/images/logos/294.png?format=webp",
        "Kyoto Sanga": "https://images.kickoffapi.com/images/logos/302.png?format=webp",
        "Machida Zelvia": "https://images.kickoffapi.com/images/logos/303.png?format=webp",
        "Mito Hollyhock": "https://images.kickoffapi.com/images/logos/305.png?format=webp",
        "Nagoya Grampus": "https://images.kickoffapi.com/images/logos/288.png?format=webp",
        "Sanfrecce Hiroshima": "https://images.kickoffapi.com/images/logos/282.png?format=webp",
        "Shimizu S-pulse": "https://images.kickoffapi.com/images/logos/283.png?format=webp",
        "Tokyo Verdy": "https://images.kickoffapi.com/images/logos/306.png?format=webp",
        "Urawa": "https://images.kickoffapi.com/images/logos/287.png?format=webp",
        "V-varen Nagasaki": "https://images.kickoffapi.com/images/logos/285.png?format=webp",
        "Vissel Kobe": "https://images.kickoffapi.com/images/logos/289.png?format=webp",
        "Yokohama F. Marinos": "https://images.kickoffapi.com/images/logos/296.png?format=webp",
    },
}


TEAM_LOGO_ALIASES: dict[str, dict[str, str]] = {
    "bundesliga": {
        "1. FC Union Berlin": "Union Berlin",
        "TSG 1899 Hoffenheim": "1899 Hoffenheim",
        "1. FSV Mainz 05": "FSV Mainz 05",
        "Bayer 04 Leverkusen": "Bayer Leverkusen",
        "SV Werder Bremen": "Werder Bremen",
        "SV 07 Elversberg": "SV Elversberg",
        "FC Bayern München": "Bayern München",
    },
}


def get_static_team_logo(competition_id: str, team_name: str) -> str | None:
    teams = TEAM_LOGOS.get(competition_id, {})
    canonical_name = TEAM_LOGO_ALIASES.get(competition_id, {}).get(team_name, team_name)
    return teams.get(canonical_name)
